---
title: "covid_19_case_definition_mexico"
author: "Isaac Núñez"
date: "11/2/2021"
output: html_document
---

```{r needed packages and saved dataframes, include = F}
library(tidyverse);library(data.table);library(lubridate); library(zoo); library(patchwork)
load("base_cdmx_v1.RDa")
load("pre_post_df_v1.RDa")
Sys.setlocale("LC_ALL", locale= "English")

```

Dates were changed to the "short" format in Excel
```{r definición de caso CDMX, include = F, run = T, echo = F, warnings= F}
base_cdmx_v1 <- fread("E:/Protocolos de investigación/CDMX/Actas de defunción/sinave_cdmx_07_02_21.csv")[,`:=`(
  fechreg=dmy(as.Date(fechreg)),
  fecha_actualizacion=dmy(as.Date(fecha_actualizacion)),
  fecinisi = dmy(as.Date(fecinisi)),
  fecingre = dmy(as.Date(fecingre))
)][,`:=`(defuncion=ifelse(fecdef!= "", T, F),
         caso_sospechoso_ssa=ifelse((tos == "SI"|
                                        cefalea == "SI"|
                                        fiebre =="SI"|
                                        disnea == "SI")&
                                       (odinogia == "SI"|
                                          calofrios == "SI"|
                                          dotoraci == "SI"|
                                          rinorrea == "SI"|
                                          artral == "SI"|
                                          mialgias == "SI"|
                                          conjun == "SI")& fecingre-fecinisi >=0&fecingre-fecinisi<=10,T,F),
         resultado_pcr = case_when(resdefin == "SARS-CoV-2"~ "POSITIVO",
                                   resdefin =="NO ADECUADO"|resdefin == "NO AMPLIFICO"|resdefin =="NO RECIBIDA"|
                                     resdefin =="NO SUBTIPIFICADO"|resdefin =="RECHAZADA" | resdefin =="SIN CELULAS"~"PERDIDA O INADECUADA",
                                   resdefin == "NEGATIVO"~"NEGATIVO",
                                   resdefin != ""~"OTRO VIRUS"),
         caso_oms_clasif = case_when(sum(tos=="SI", fiebre=="SI",ataedoge=="SI", cefalea=="SI", 
                                          mialgias=="SI", odinogia=="SI", vomito=="SI",conjun=="SI",
                                          rinorrea=="SI",disnea=="SI",diarrea=="SI", na.rm=T)>=3&
                                       conocaso=="SI"&(digcline=="SI"|fecdef!= "")~"probable",
                                      (tos==T & fiebre==T)|
                                       (sum(tos=="SI", fiebre=="SI",ataedoge=="SI", cefalea=="SI", 
                                           mialgias=="SI", odinogia=="SI", vomito=="SI",conjun=="SI",
                                           rinorrea=="SI",disnea=="SI",diarrea=="SI", na.rm=T)>=3)~"sospechoso"))][fechreg >= "2020-03-24",][,resultado_final := if_else(resultado_pcr == "POSITIVO" | antigencovid == "POSITIVO", 
                                                        T, F)][,sospechoso_oms:=if_else((tos==T & fiebre==T)|
                                       (sum(tos=="SI", fiebre=="SI",ataedoge=="SI", cefalea=="SI", 
                                           mialgias=="SI", odinogia=="SI", vomito=="SI",conjun=="SI",
                                           rinorrea=="SI",disnea=="SI",diarrea=="SI", na.rm=T)>=3), T, F)][!is.na(resultado_pcr) & 
                                                                                                             resultado_pcr != "PERDIDA O INADECUADA",][,sospechoso_ssa_inicial := if_else(sum(tos=="SI", fiebre =="SI",
                                                                                     cefalea=="SI", na.rm = T)>=3 &
                                                                                   (disnea == "SI"| artral == "SI"|
                                                                                      mialgias == "SI"| odinogia == "SI" |
                                                                                      rinorrea == "SI"| conjun == "SI"| 
                                                                                    dotoraci == "SI") &
                                                                                   fecingre-fecinisi >=0 &fecingre-fecinisi<=7,T,F)][,
                                                                                     ssa_confirmed_epi:=if_else(caso_sospechoso_ssa == T&
                                                                                                                  conocaso == "SI", T, F)
                                                                                   ]

#save(base_cdmx_v1, file="base_cdmx_v1.RDa")

#La definición de caso probable trae consigo una probabilidad pre-prueba>50% en cuanto a prueba de antígeno positiva
#Esto es vital con fines epidemiológicos.
#Tengo que ver como cambió esta probabilidad conforme el paso del tiempo
#El hecho de que TODOS los pacientes hayan sido casos sospechosos con definición de la OMS y NO con la definición de la SSA es vital porque esto se traduce a que muchos casos sospechosos NO SE ESTÁN CONSIDERANDO.

table(PCR=base_cdmx_v1$resultado_pcr, OMS=base_cdmx_v1$caso_oms_clasif)
table(ANTIGENO=base_cdmx_v1$antigencovid, OMS=base_cdmx_v1$caso_oms_clasif)

#les hicieron PCR
nrow(base_cdmx_v1)-sum(is.na(base_cdmx_v1$resultado_pcr))
#les hicieron pcr y no antígeno
glimpse(base_cdmx_v1[!is.na(resultado_pcr)&antigencovid=="",])

#les hicieron antigeno
nrow(base_cdmx_v1)-sum(base_cdmx_v1$antigencovid == "")
#les hicieron antigeno y no tenían pcr
table(base_cdmx_v1[is.na(resultado_pcr),]$antigencovid
      )
```

```{r sensitivity specificity PPV NPV, include = F}
#MEXICO FIRST DEFINITION OF SUSPECTED CASE
a_ssa_in <- sum(base_cdmx_v1$sospechoso_ssa_inicial==T&base_cdmx_v1$resultado_final==T)
b_ssa_in <- sum(base_cdmx_v1$sospechoso_ssa_inicial==T&base_cdmx_v1$resultado_final==F)
c_ssa_in <- sum(base_cdmx_v1$sospechoso_ssa_inicial==F&base_cdmx_v1$resultado_final==T)
d_ssa_in <- sum(base_cdmx_v1$sospechoso_ssa_inicial==F&base_cdmx_v1$resultado_final==F)
#Are suspected cases
a_ssa_in+b_ssa_in
round((a_ssa_in+b_ssa_in)/(a_ssa_in+b_ssa_in+c_ssa_in+d_ssa_in),2)
#Sensitivity
sens_ssa_in <- round(a_ssa_in/(a_ssa_in+c_ssa_in), 2)
#Specificity
espec_ssa_in <- round(d_ssa_in/(b_ssa_in+d_ssa_in), 2)
#Global PPV
ppv_ssa_in <- round(a_ssa_in/(a_ssa_in+b_ssa_in), 2)
#Global NPV
npv_ssa_in <- round(d_ssa_in/(c_ssa_in+d_ssa_in), 2)
#Positive LR
pos_lr_ssa_in <- round(sens_ssa_in/(1-espec_ssa_in),2)
#Negative LR
neg_lr_ssa_in <- round((1-sens_ssa_in)/espec_ssa_in,2)


#MEXICO SECOND DEFINITION OF SUSPECTED CASE
a_ssa <- sum(base_cdmx_v1$caso_sospechoso_ssa==T&base_cdmx_v1$resultado_final==T)
b_ssa <- sum(base_cdmx_v1$caso_sospechoso_ssa==T&base_cdmx_v1$resultado_final==F)
c_ssa <- sum(base_cdmx_v1$caso_sospechoso_ssa==F&base_cdmx_v1$resultado_final==T)
d_ssa <- sum(base_cdmx_v1$caso_sospechoso_ssa==F&base_cdmx_v1$resultado_final==F)
#Are suspected cases
a_ssa+b_ssa
round((a_ssa+b_ssa)/(a_ssa+b_ssa+c_ssa+d_ssa),2)
#Sensitivity
sens_ssa <- round(a_ssa/(a_ssa+c_ssa), 2)
#Specificity
espec_ssa <- round(d_ssa/(b_ssa+d_ssa), 2)
#Global PPV
ppv_ssa <- round(a_ssa/(a_ssa+b_ssa), 2)
#Global NPV
npv_ssa <- round(d_ssa/(c_ssa+d_ssa), 2)
#Positive LR
pos_lr_ssa <- round(sens_ssa/(1-espec_ssa),2)
#Negative LR
neg_lr_ssa <- round((1-sens_ssa)/espec_ssa,2)

#MEXICO EPI DEFINITION OF CONFIRMED CASE
a_ssa_epi <- sum(base_cdmx_v1$ssa_confirmed_epi==T&base_cdmx_v1$resultado_final==T)
b_ssa_epi <- sum(base_cdmx_v1$ssa_confirmed_epi==T&base_cdmx_v1$resultado_final==F)
c_ssa_epi <- sum(base_cdmx_v1$ssa_confirmed_epi==F&base_cdmx_v1$resultado_final==T)
d_ssa_epi <- sum(base_cdmx_v1$ssa_confirmed_epi==F&base_cdmx_v1$resultado_final==F)
#Are suspected cases
a_ssa_epi+b_ssa_epi
round((a_ssa_epi+b_ssa_epi)/(a_ssa_epi+b_ssa_epi+c_ssa_epi+d_ssa_epi),2)
#Sensitivity
sens_ssa_epi <- round(a_ssa_epi/(a_ssa_epi+c_ssa_epi), 2)
#Specificity
espec_ssa_epi <- round(d_ssa_epi/(b_ssa_epi+d_ssa_epi), 2)
#Global PPV
ppv_ssa_epi <- round(a_ssa_epi/(a_ssa_epi+b_ssa_epi), 2)
#Global NPV
npv_ssa_epi <- round(d_ssa_epi/(c_ssa_epi+d_ssa_epi), 2)
#Positive LR
pos_lr_ssa_epi <- round(sens_ssa_epi/(1-espec_ssa_epi),2)
#Negative LR
neg_lr_ssa_epi <- round((1-sens_ssa_epi)/espec_ssa_epi,2)

#WHO DEFINITION OF SUSPECTED CASE
a_who_s <- sum(base_cdmx_v1$sospechoso_oms==T&base_cdmx_v1$resultado_final==T)
b_who_s <- sum(base_cdmx_v1$sospechoso_oms==T&base_cdmx_v1$resultado_final==F)
c_who_s <- sum(base_cdmx_v1$sospechoso_oms==F&base_cdmx_v1$resultado_final==T)
d_who_s <- sum(base_cdmx_v1$sospechoso_oms==F&base_cdmx_v1$resultado_final==F)
#Sensitivity
sens_who_s <- round(a_who_s/(a_who_s+c_who_s), 2)
#Specificity
espec_who_s <- round(d_who_s/(b_who_s+d_who_s), 2)
#Global PPV
ppv_who_s <- round(a_who_s/(a_who_s+b_who_s), 2)
#Global NPV
npv_who_s <- round(d_who_s/(b_who_s+c_who_s), 2)
#Positive LR
pos_lr_who_s <- round(sens_who_s/(1-espec_who_s),2)
#Negative LR
neg_lr_who_s <- round((1-sens_who_s)/espec_who_s,2)

#WHO DEFINITION OF PROBABLE CASE
a_who_p <- sum(base_cdmx_v1$caso_oms_clasif=="probable"&base_cdmx_v1$resultado_final==T)
b_who_p <- sum(base_cdmx_v1$caso_oms_clasif=="probable"&base_cdmx_v1$resultado_final==F)
c_who_p <- sum(base_cdmx_v1$caso_oms_clasif!="probable"&base_cdmx_v1$resultado_final==T)
d_who_p <- sum(base_cdmx_v1$caso_oms_clasif!="probable"&base_cdmx_v1$resultado_final==F)
a_who_p+b_who_p
(a_who_p+b_who_p)/(a_who_p+b_who_p+c_who_p+d_who_p)

#Sensitivity
sens_who_p <- round(a_who_p/(a_who_p+c_who_p), 2)
#Specificity
espec_who_p <- round(d_who_p/(b_who_p+d_who_p), 2)
#Global PPV
ppv_who_p <- round(a_who_p/(a_who_p+b_who_p), 2)
#Global NPV
npv_who_p <- round(d_who_p/(c_who_p+d_who_p), 2)
#Positive LR
pos_lr_who_p <- round(sens_who_p/(1-espec_who_p),2)
#Negative LR
neg_lr_who_p <- round((1-sens_who_p)/espec_who_p,2)
```

```{r post_test probabilities, include = F}
pre_post_df_ssa_in <- group_by(base_cdmx_v1, by= fechreg) %>% 
       count() %>% 
  rename(fechreg=by) %>% 
  left_join(select(base_cdmx_v1, fechreg, resultado_final) %>% 
              group_by(fechreg) %>% 
            summarise(positivos = sum(resultado_final == T)), by = "fechreg") %>% 
  mutate(pre_test_prob = round(positivos/n, 2),
         pre_test_odds = pre_test_prob/(1-pre_test_prob),
         post_test_prob_pos = round(pre_test_odds*pos_lr_ssa_in,2)/(1+round(pre_test_odds*pos_lr_ssa_in,2)),
         post_test_prob_neg = round(pre_test_odds*neg_lr_ssa_in,2)/(1+round(pre_test_odds*neg_lr_ssa_in,2)),
         definicion = "Mx suspected case first")

pre_post_df_ssa <- group_by(base_cdmx_v1, by= fechreg) %>% 
       count() %>% 
  rename(fechreg=by) %>% 
  left_join(select(base_cdmx_v1, fechreg, resultado_final) %>% 
              group_by(fechreg) %>% 
            summarise(positivos = sum(resultado_final == T)), by = "fechreg") %>% 
  mutate(pre_test_prob = round(positivos/n, 2),
         pre_test_odds = pre_test_prob/(1-pre_test_prob),
         post_test_prob_pos = round(pre_test_odds*pos_lr_ssa,2)/(1+round(pre_test_odds*pos_lr_ssa,2)),
         post_test_prob_neg = round(pre_test_odds*neg_lr_ssa,2)/(1+round(pre_test_odds*neg_lr_ssa,2)),
         definicion = "Mx suspected case second")

pre_post_df_ssa_epi <- group_by(base_cdmx_v1, by= fechreg) %>% 
       count() %>% 
  rename(fechreg=by) %>% 
  left_join(select(base_cdmx_v1, fechreg, resultado_final) %>% 
              group_by(fechreg) %>% 
            summarise(positivos = sum(resultado_final == T)), by = "fechreg") %>% 
  mutate(pre_test_prob = round(positivos/n, 2),
         pre_test_odds = pre_test_prob/(1-pre_test_prob),
         post_test_prob_pos = round(pre_test_odds*pos_lr_ssa_epi,2)/(1+round(pre_test_odds*pos_lr_ssa_epi,2)),
         post_test_prob_neg = round(pre_test_odds*neg_lr_ssa_epi,2)/(1+round(pre_test_odds*neg_lr_ssa_epi,2)),
         definicion = "Mx confirmed case epi")

pre_post_df_who_s <- group_by(base_cdmx_v1, by= fechreg) %>% 
       count() %>% 
  rename(fechreg=by) %>% 
  left_join(select(base_cdmx_v1, fechreg, resultado_final) %>% 
              group_by(fechreg) %>% 
            summarise(positivos = sum(resultado_final == T)), by = "fechreg") %>% 
  mutate(pre_test_prob = round(positivos/n, 2),
         pre_test_odds = pre_test_prob/(1-pre_test_prob),
         post_test_prob_pos = round(pre_test_odds*pos_lr_who_s,2)/(1+round(pre_test_odds*pos_lr_who_s,2)),
         post_test_prob_neg = round(pre_test_odds*neg_lr_who_s,2)/(1+round(pre_test_odds*neg_lr_who_s,2)),
         definicion = "WHO suspected case")

pre_post_df_who_p <- group_by(base_cdmx_v1, by= fechreg) %>% 
       count() %>% 
  rename(fechreg=by) %>% 
  left_join(select(base_cdmx_v1, fechreg, resultado_final) %>% 
              group_by(fechreg) %>% 
            summarise(positivos = sum(resultado_final == T)), by = "fechreg") %>% 
  mutate(pre_test_prob = round(positivos/n, 2),
         pre_test_odds = pre_test_prob/(1-pre_test_prob),
         post_test_prob_pos = round(pre_test_odds*pos_lr_who_p,2)/(1+round(pre_test_odds*pos_lr_who_p,2)),
         post_test_prob_neg = round(pre_test_odds*neg_lr_who_p,2)/(1+round(pre_test_odds*neg_lr_who_p,2)),
         definicion = "WHO probable case")


pre_post_df <- rbind(pre_post_df_ssa_in,pre_post_df_ssa,pre_post_df_ssa_epi,pre_post_df_who_s,pre_post_df_who_p)
save(pre_post_df, file = "pre_post_df.RDa")


pre_post_df$rol_mean_pos_ssa_in <-  rollmean(filter(pre_post_df,definicion == "Mx suspected case in")$post_test_prob_pos, 7,
                                          align="right", fill =0)


pre_post_df$rol_mean_neg_ssa_in <-  rollmean(filter(pre_post_df,definicion == "Mx suspected case in")$post_test_prob_neg, 7,
                                          align="right", fill =0)

pre_post_df$rol_mean_pos_ssa <-  rollmean(filter(pre_post_df,definicion == "Mx suspected case")$post_test_prob_pos, 7,
                                          align="right", fill =0)
pre_post_df$rol_mean_neg_ssa <-  rollmean(filter(pre_post_df,definicion == "Mx suspected case")$post_test_prob_neg, 7,
                                          align="right", fill =0)

pre_post_df$rol_mean_pos_ssa_epi <-  rollmean(filter(pre_post_df,definicion == "Mx confirmed case epi")$post_test_prob_pos, 7,
                                          align="right", fill =0)
pre_post_df$rol_mean_neg_ssa_epi <-  rollmean(filter(pre_post_df,definicion == "Mx confirmed case epi")$post_test_prob_neg, 7,
                                          align="right", fill =0)

pre_post_df$rol_mean_pos_who_s <-  rollmean(filter(pre_post_df,definicion == "WHO suspected case")$post_test_prob_pos, 7,
                                          align="right", fill =0)
pre_post_df$rol_mean_neg_who_s <-  rollmean(filter(pre_post_df,definicion == "WHO suspected case")$post_test_prob_neg, 7,
                                          align="right", fill =0)

pre_post_df$rol_mean_pos_who_p <-  rollmean(filter(pre_post_df,definicion == "WHO probable case")$post_test_prob_pos, 7,
                                          align="right", fill =0)
pre_post_df$rol_mean_neg_who_p <-  rollmean(filter(pre_post_df,definicion == "WHO probable case")$post_test_prob_neg, 7,
                                          align="right", fill =0)
```


```{r post_test probabilities plot, include = F}
#GRAPHS
plot_positive_case <- ggplot(pre_post_df, aes(x=fechreg, y = round(rollmean(post_test_prob_pos, 7,
                                            align="right", fill =NA)*100, 0), shape = definicion))+
  geom_point(size = 2)+
  geom_line()+
  scale_shape_manual(values=c(0,1,2,15,16))+
  scale_y_continuous(breaks = seq(from=10, to=100, by = 10),
                     limits= c(0,100))+
  scale_x_date(date_breaks = "1 month",
               date_labels ="%b %y")+
  theme_bw()+
  ggtitle("Positive case definition")+
  labs(y="Post-test probability of COVID-19 (%)",
       x="Date",
       title = "A")+
  theme(legend.title = element_blank(),
        legend.text = element_text(size=5, 
                                     face="bold"),
        legend.position = c(.8, .82),
        axis.text.x = element_text(angle = 90, vjust = .25, hjust = 0.95, 
                               size = 14, face = "bold", colour="black"),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.y = element_text(size = 14, face = "bold", colour = "black"),
        plot.title = element_text(size = 14, face = "bold"))

#scale_linetype_manual(values=c("dotdash", "dotted", "longdash", "twodash"))
#  legend.position = "none"
  
plot_negative_case <- ggplot(pre_post_df, aes(x=fechreg, y = round(rollmean(post_test_prob_neg, 7,
                                            align="right", fill =NA)*100,0), shape = definicion))+
  geom_point(size = c(rep(0,316),rep(2,316),rep(0,316),rep(2,316),rep(0,316)))+
  geom_line()+
  scale_shape_manual(values=c(0,1,2,15,16))+
  scale_y_continuous(breaks = seq(from=10, to=100, by = 10),
                     limits= c(0,100))+
  scale_x_date(date_breaks = "1 month",
               date_labels ="%b %y")+
  theme_bw()+
  ggtitle("Negative case definition")+
  labs(y="",
       x="Date",
       title = "B")+
  theme(legend.position="none",
    axis.text.x = element_text(angle = 90, vjust = .25, hjust = 0.95, 
                               size = 14, face = "bold", colour="black"),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.y = element_text(size = 14, face = "bold", colour = "black"),
        plot.title = element_text(size = 14, face = "bold"))


combined_post_test_plots <- plot_positive_case+plot_negative_case

##################################################################

plot_positive_case_line <- ggplot(pre_post_df, aes(x=fechreg, y = round(rollmean(post_test_prob_pos, 7,
                                            align="right", fill =NA)*100,0), linetype = definicion, colour = definicion))+
  geom_line(size = c(rep(0,316),rep(1,316),rep(1,316),rep(1,316),rep(1,316)))+
  scale_linetype_manual(values=c("solid", "dotted", "longdash","twodash", "dotdash"))+
  scale_y_continuous(breaks = seq(from=0, to=100, by = 10),
                     limits= c(0,100))+
  scale_x_date(date_breaks = "1 month",
               date_labels ="%b %y")+
  scale_colour_brewer(palette="Dark2")+
  theme_bw()+
  ggtitle("Positive case definition")+
  labs(y="Post-test probability of COVID-19 (%)",
       x="Date",
       title = "A")+
  theme(legend.title = element_blank(),
        legend.text = element_text(size=5, 
                                     face="bold"),
        legend.position = c(.8, .85),
        axis.text.x = element_text(angle = 90, vjust = .25, hjust = 0.95, 
                               size = 14, face = "bold", colour="black"),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.y = element_text(size = 14, face = "bold", colour = "black"),
        plot.title = element_text(size = 14, face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"))

  
plot_negative_case_line <- ggplot(pre_post_df, aes(x=fechreg, y = round(rollmean(post_test_prob_neg, 7,
                                            align="right", fill =NA)*100,0), linetype = definicion, colour = definicion))+
  geom_line(size = c(rep(0,316),rep(1,316),rep(1,316),rep(1,316),rep(1,316)))+
  scale_linetype_manual(values=c("solid", "dotted", "longdash","twodash", "dotdash"))+
  scale_y_continuous(breaks = seq(from=0, to=100, by = 10),
                     limits= c(0,100))+
  scale_x_date(date_breaks = "1 month",
               date_labels ="%b %y")+
  scale_colour_brewer(palette="Dark2")+
  theme_bw()+
  ggtitle("Negative case definition")+
  labs(y="Post-test probability of COVID-19 (%)",
       x="Date",
       title = "B")+
  theme(legend.position="none",
        axis.text.x = element_text(angle = 90, vjust = .25, hjust = 0.95, 
                                   size = 14, face = "bold", colour="black"),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.y = element_text(size = 14, face = "bold", colour = "black"),
        plot.title = element_text(size = 14, face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"))

combined_post_test_plots_line <- plot_positive_case_line/plot_negative_case_line



plot_negative_case_line_1 <- ggplot(pre_post_df, aes(x=fechreg, y = rollmean(post_test_prob_neg, 7,
                                            align="right", fill =NA), linetype = definicion))+
  geom_line(size = 0.8)+
  scale_linetype_manual(values=c("dotdash", "dotted", "longdash","twodash", "solid"))+
  scale_y_continuous(breaks = seq(from=0.1, to=1, by = 0.1),
                     limits= c(0,1))+
  scale_x_date(date_breaks = "1 month",
               date_labels ="%b %y")+
  theme_bw()+
  ggtitle("Negative case definition")+
  labs(y="",
       x="Date",
       title = "B")+
  theme(legend.position="bottom",
    axis.text.x = element_text(angle = 90, vjust = .25, hjust = 0.95, 
                               size = 14, face = "bold", colour="black"),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.y = element_text(size = 14, face = "bold", colour = "black"),
        plot.title = element_text(size = 14, face = "bold"))

#save(pre_post_df, file="pre_post_df_v1.RDa")

###########################################
#COLOUR GRAPHS


plot_positive_case_line_colour <- ggplot(pre_post_df, aes(x=fechreg, y = rollmean(post_test_prob_pos, 7,
                                            align="right", fill =NA), colour = definicion))+
  geom_line(size = 0.8)+
  scale_colour_brewer(palette="Dark2")+
  scale_y_continuous(breaks = seq(from=0.1, to=1, by = 0.1),
                     limits= c(0,1))+
  scale_x_date(date_breaks = "1 month",
               date_labels ="%b %y")+
  theme_bw()+
  ggtitle("Positive case definition")+
  labs(y="Post-test probability of COVID-19",
       x="Date",
       title = "A")+
  theme(
        legend.title = element_blank(),
        legend.text = element_text(size=5, 
                                     face="bold"),
        legend.position = c(.8, .82),
        axis.text.x = element_text(angle = 90, vjust = .25, hjust = 0.95, 
                               size = 14, face = "bold", colour="black"),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.y = element_text(size = 14, face = "bold", colour = "black"),
        plot.title = element_text(size = 14, face = "bold"))

  
plot_negative_case_line_colour <- ggplot(pre_post_df, aes(x=fechreg, y = rollmean(post_test_prob_neg, 7,
                                            align="right", fill =NA), colour = definicion))+
  geom_line(size = 0.8)+
  scale_colour_brewer(palette="Dark2")+
  scale_linetype_manual(values=c("dotdash", "dotted", "longdash","twodash", "solid"))+
  scale_y_continuous(breaks = seq(from=0.1, to=1, by = 0.1),
                     limits= c(0,1))+
  scale_x_date(date_breaks = "1 month",
               date_labels ="%b %y")+
  theme_bw()+
  ggtitle("Negative case definition")+
  labs(y="",
       x="Date",
       title = "B")+
  theme(legend.position="none",
    axis.text.x = element_text(angle = 90, vjust = .25, hjust = 0.95, 
                               size = 14, face = "bold", colour="black"),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.y = element_text(size = 14, face = "bold", colour = "black"),
        plot.title = element_text(size = 14, face = "bold"))

combined_post_test_plots_line_colour <- plot_positive_case_line_colour+plot_negative_case_line_colour
#Lo estoy guardando en tamaño 6x10


plot_negative_case_line_1 <- ggplot(pre_post_df, aes(x=fechreg, y = rollmean(post_test_prob_neg, 7,
                                            align="right", fill =NA), linetype = definicion))+
  geom_line(size = 0.8)+
  scale_linetype_manual(values=c("dotdash", "dotted", "longdash","twodash", "solid"))+
  scale_y_continuous(breaks = seq(from=0.1, to=1, by = 0.1),
                     limits= c(0,1))+
  scale_x_date(date_breaks = "1 month",
               date_labels ="%b %y")+
  theme_bw()+
  ggtitle("Negative case definition")+
  labs(y="",
       x="Date",
       title = "B")+
  theme(legend.position="bottom",
    axis.text.x = element_text(angle = 90, vjust = .25, hjust = 0.95, 
                               size = 14, face = "bold", colour="black"),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.y = element_text(size = 14, face = "bold", colour = "black"),
        plot.title = element_text(size = 14, face = "bold"))
```

```{r manuscript text, include = F, run = T}
View(pre_post_df %>% 
  group_by(definicion) %>% 
  summarise(resumen_post_pos_min = min(post_test_prob_pos),
            resumen_post_pos_max = max(post_test_prob_pos),
            resumen_post_pos_mean = mean(post_test_prob_pos),
            resumen_post_pos_sd = sd(post_test_prob_pos),
  resumen_post_neg_min = min(post_test_prob_neg),
            resumen_post_neg_max = max(post_test_prob_neg),
            resumen_post_neg_mean = mean(post_test_prob_neg),
            resumen_post_neg_sd = sd(post_test_prob_neg)))

            
table(PCR=base_cdmx_v1$resultado_pcr, ANTIGENO= base_cdmx_v1$antigencovid)

```



